# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.


# Inherit common configuration
$(call inherit-product, device/samsung/aries-common/device_base.mk)

# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
DEVICE_PACKAGE_OVERLAYS := device/samsung/galaxys4gmtd/overlay

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
	device/samsung/galaxys4gmtd/rdisk/vold.fstab:system/etc/vold.fstab \
	device/samsung/galaxys4gmtd/sound/asound.conf:system/etc/asound.conf


# Init files
PRODUCT_COPY_FILES += \
	device/samsung/galaxys4gmtd/rdisk/init.aries.rc:root/init.aries.rc \
	device/samsung/galaxys4gmtd/rdisk/init.aries.gps.rc:root/init.aries.gps.rc \
	device/samsung/galaxys4gmtd/rdisk/init.aries.usb.rc:root/init.aries.usb.rc \
	device/samsung/galaxys4gmtd/rdisk/init.aries.usb.rc:recovery/root/usb.rc \
	device/samsung/galaxys4gmtd/rdisk/lpm.rc:root/lpm.rc \
	device/samsung/galaxys4gmtd/rdisk/ueventd.aries.rc:root/ueventd.aries.rc

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	device/samsung/galaxys4gmtd/prebuilt/key/aries-keypad.kl:system/usr/keylayout/aries-keypad.kl
	
# GPS 
PRODUCT_PACKAGES += \
	gps.aries

PRODUCT_COPY_FILES += \
	device/samsung/galaxys4gmtd/updater.sh:updater.sh

$(call inherit-product-if-exists, vendor/samsung/galaxys4gmtd/galaxys4gmtd-vendor.mk)
